# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('custom_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom id')),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transacao')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da transacao')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Item')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('month_value_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('month_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Valor mensal')),
                ('task_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite mensal')),
                ('custom_pricing', models.BooleanField(default=False, verbose_name='Preço customizado')),
                ('custom_pricing_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição para preço customizado')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['month_value'],
            },
        ),
        migrations.CreateModel(
            name='PlanOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subscription_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
                ('cancelation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de cancelamento')),
                ('month_value_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('month_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Valor mensal')),
                ('task_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite mensal')),
            ],
            options={
                'ordering': ['office'],
            },
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo')),
                ('card_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome no cartão')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF/CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefone')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'ordering': ['office', 'card_name'],
            },
        ),
    ]
