# Override de produção. Ative com: make set_env_production
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./containers/nginx/templates:/etc/nginx/templates:ro
      - ./containers/nginx/certs:/etc/nginx/certs:ro
      - web-static:/usr/share/nginx/html/static:ro
      - web-media:/usr/share/nginx/html/media:ro

  flower:
    ports:
      - "127.0.0.1:5555:5555"
