# Override de desenvolvimento. Ative com: make set_env_development
services:
  web:
    build:
      args:
        requirements_file: development.txt
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      mail:
        condition: service_started

  ws:
    ports:
      - "8002:8002"

  worker:
    build:
      args:
        requirements_file: development.txt

  nginx:
    ports:
      - "8080:80"

  db:
    ports:
      - "57002:5432"

  redis:
    ports:
      - "57003:6379"

  queues:
    ports:
      - "8083:15672"
      - "5672:5672"

  flower:
    ports:
      - "5555:5555"

  postfix:
    profiles: ["production"]

  mail:
    image: axllent/mailpit:latest
    ports:
      - "8026:8025"
      - "1026:1025"
    restart: unless-stopped
