[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
python_files = tests.py test_*.py *_tests.py
xfail_strict = true
addopts = --cov-branch --cov-report term --cov=task --cov=core --cov=lawsuit --cov=ecm --cov=survey --cov=financial --cov=billing --cov=manager --cov=dashboard --cov=chat --cov=etl
