# Generated by Django 5.2.17 on 2026-09-08 20:04

import core.models
import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_commission_requestor', models.FloatField(default=0.025, verbose_name='Taxa de comissão do solicitante')),
                ('rate_commission_correspondent', models.FloatField(default=0.1, verbose_name='Taxa de comissão do correspondente')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=2555, verbose_name='Área de atuação')),
            ],
            options={
                'verbose_name': 'Área de atuação',
                'verbose_name_plural': 'Áreas de atuação',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('name', models.CharField(max_length=255, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_administrative_menus', models.BooleanField(default=False, verbose_name='Mostrar menus administrativos')),
            ],
            options={
                'verbose_name': 'Usuario da empresa',
                'verbose_name_plural': 'Usuário das empresas',
            },
        ),
        migrations.CreateModel(
            name='ContactMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('notes', models.CharField(blank=True, max_length=400, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Mecanismo de contato',
                'verbose_name_plural': 'Mecanismos de contato',
                'db_table': 'contact_mechanism',
            },
        ),
        migrations.CreateModel(
            name='ContactMechanismType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('type_contact_mechanism_type', models.IntegerField(choices=[(1, 'INVÁLIDO'), (2, 'TELEFONE'), (3, 'E-MAIL'), (4, 'SKYPE'), (5, 'WHATSAPP'), (6, 'FACEBOOK'), (7, 'SITE'), (8, 'LINKEDIN'), (9, 'INSTAGRAM'), (10, 'SNAPCHAT')], default=2, verbose_name='Tipo')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'contact_mechanism_type',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
        migrations.CreateModel(
            name='ControlFirstAccessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='Data do primeiro acesso.')),
            ],
            options={
                'verbose_name': 'Controle de primeiro acesso',
                'verbose_name_plural': 'Controle de primeiro acesso',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateTimeField(verbose_name='Data inicial')),
                ('finish_date', models.DateTimeField(verbose_name='Data final')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Mensagens Customizadas',
                'verbose_name_plural': 'Mensagens Customizadas',
            },
        ),
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email_to_notification', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para receber notificações')),
                ('i_work_alone', models.BooleanField(default=True)),
                ('show_task_in_admin_dash', models.BooleanField(default=True, verbose_name='Mostrar as OSs deste escritório no Dash')),
            ],
            options={
                'verbose_name': 'Configurações por escritório',
            },
        ),
        migrations.CreateModel(
            name='DefaultOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Escritório Padrão',
                'verbose_name_plural': 'Escritórios Padrão',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do template')),
                ('template_id', models.CharField(max_length=255, verbose_name='Template (caminho do arquivo .html)')),
            ],
            options={
                'verbose_name': 'E-mail templates',
            },
        ),
        migrations.CreateModel(
            name='ExternalApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=255, unique=True, verbose_name='client ID')),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated', verbose_name='redirect URIs')),
                ('post_logout_redirect_uris', models.TextField(blank=True, default='', help_text='Allowed Post Logout URIs list, space separated', verbose_name='post logout redirect URIs')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32, verbose_name='client type')),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('urn:ietf:params:oauth:grant-type:device_code', 'Device Code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=44, verbose_name='authorization grant type')),
                ('client_secret', oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Client secret for authentication', max_length=255, verbose_name='client secret')),
                ('hash_client_secret', models.BooleanField(default=True, verbose_name='hash client secret')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('skip_authorization', models.BooleanField(default=False, verbose_name='skip authorization')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('algorithm', models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5, verbose_name='algorithm')),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated', verbose_name='allowed origins')),
                ('registration_source', models.CharField(choices=[('manual', 'Manual'), ('dcr', 'Dynamic Client Registration'), ('cimd', 'Client ID Metadata Document')], default='manual', help_text='How this application was registered (manual, DCR per RFC 7591, or CIMD)', max_length=32, verbose_name='registration source')),
                ('cimd_expires_at', models.DateTimeField(blank=True, default=None, help_text='When the cached Client ID Metadata Document should be re-fetched', null=True, verbose_name='CIMD expires at')),
            ],
            options={
                'verbose_name': 'Aplicação externa',
                'verbose_name_plural': 'Aplicações externas',
            },
        ),
        migrations.CreateModel(
            name='ImportXlsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('file_xls', models.FileField(upload_to=core.models.get_dir_name, verbose_name='Arquivo')),
                ('start', models.DateTimeField(verbose_name='Início processo')),
                ('end', models.DateTimeField(null=True, verbose_name='Fim processo')),
                ('log_file', models.JSONField(blank=True, null=True, verbose_name='Log do processo')),
            ],
            options={
                'verbose_name': 'Arquivos Importados para inserção em lote',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('A', 'ACCEPTED'), ('R', 'REFUSED'), ('N', 'NOT REVIEWED'), ('E', 'EXTERNAL')], default='N', max_length=1, verbose_name='Status')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('invite_code', models.CharField(blank=True, default=core.models._create_hash, max_length=50, null=True, unique=True, verbose_name='Código do convite')),
                ('invite_from', models.CharField(choices=[('P', 'PERSON'), ('O', 'OFFICE')], default='O', max_length=1, verbose_name='Origem do convite')),
            ],
            options={
                'verbose_name': 'Convite',
            },
        ),
        migrations.CreateModel(
            name='InviteOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('A', 'ACCEPTED'), ('R', 'REFUSED'), ('N', 'NOT REVIEWED'), ('E', 'EXTERNAL')], default='N', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Convite para escritório',
                'verbose_name_plural': 'Convites para escritórios',
            },
        ),
        migrations.CreateModel(
            name='ModelExportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('legacy_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado')),
                ('system_prefix', models.CharField(blank=True, choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'), ('eLaw', 'Elaw')], max_length=255, null=True, verbose_name='Prefixo do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão social/Nome completo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia/Apelido')),
                ('is_lawyer', models.BooleanField(default=False, verbose_name='É Advogado?')),
                ('legal_type', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default=core.models.LegalType['JURIDICA'], max_length=1, verbose_name='Tipo')),
                ('is_customer', models.BooleanField(default=False, verbose_name='É Cliente?')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='É Fornecedor?')),
                ('import_from_legacy', models.BooleanField(default=False, verbose_name='Importar OSs do sistema de origem para esse cliente')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('public_office', models.BooleanField(default=False, verbose_name='Escritório público')),
                ('use_service_old', models.BooleanField(default=True, verbose_name='Possuo equipe de conferência de dados na delegação e validação da OS')),
                ('use_etl_old', models.BooleanField(default=True, verbose_name='Possuo processo de importação de dados de outros sistemas')),
                ('cpf_cnpj', models.CharField(max_length=255, null=True, unique=True, verbose_name='CPF/CNPJ')),
            ],
            options={
                'verbose_name': 'Escritório',
            },
        ),
        migrations.CreateModel(
            name='OfficeMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do grupo')),
            ],
            options={
                'verbose_name': 'Rede de escritórios',
                'verbose_name_plural': 'Redes de escritórios',
            },
        ),
        migrations.CreateModel(
            name='OfficeOffices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Relacionamento entre Escritórios',
                'verbose_name_plural': 'Relacionamentos entre Escritórios',
                'ordering': ('from_office__legal_name', 'to_office__legal_name'),
            },
        ),
        migrations.CreateModel(
            name='OfficeRelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Grupo por escritório',
                'verbose_name_plural': 'Grupos por escritório',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('legacy_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado')),
                ('system_prefix', models.CharField(blank=True, choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'), ('eLaw', 'Elaw')], max_length=255, null=True, verbose_name='Prefixo do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão social/Nome completo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia/Apelido')),
                ('is_lawyer', models.BooleanField(default=False, verbose_name='É Advogado?')),
                ('legal_type', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default=core.models.LegalType['JURIDICA'], max_length=1, verbose_name='Tipo')),
                ('is_customer', models.BooleanField(default=False, verbose_name='É Cliente?')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='É Fornecedor?')),
                ('import_from_legacy', models.BooleanField(default=False, verbose_name='Importar OSs do sistema de origem para esse cliente')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF/CNPJ')),
                ('refunds_correspondent_service', models.BooleanField(default=False, verbose_name='Cliente reembolsa valor gasto com serviço de correspondência')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'person',
                'ordering': ['legal_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('initials', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'db_table': 'state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'db_table': 'address_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('city_region', models.CharField(max_length=255, verbose_name='Bairro')),
                ('zip_code', models.CharField(max_length=255, verbose_name='CEP')),
                ('home_address', models.BooleanField(blank=True, default=False)),
                ('business_address', models.BooleanField(blank=True, default=False)),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.addresstype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255)),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'verbose_name': 'Cidade',
                'db_table': 'city',
            },
        ),
    ]
