# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('execution_date_start', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inicio')),
                ('execution_date_finish', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fim')),
                ('name', models.CharField(editable=False, max_length=100, verbose_name='ETL')),
                ('status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
                ('read_quantity', models.IntegerField(default=0, editable=False, verbose_name='Quantidade Lida')),
                ('imported_quantity', models.IntegerField(default=0, editable=False, verbose_name='Quantidade importada')),
                ('executed_query', models.TextField(blank=True, editable=False, null=True, verbose_name='Query executada')),
                ('db_name_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='DB de origem')),
                ('db_host_source', models.CharField(blank=True, max_length=20, null=True, verbose_name='Host do db de origem')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Dashboard ETL',
                'verbose_name_plural': 'Dashboard ETL',
                'db_table': 'dashboard_etl',
                'ordering': ('-execution_date_start',),
            },
        ),
        migrations.CreateModel(
            name='ErrorETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('error', models.TextField(blank=True, editable=False, null=True, verbose_name='Descrição do erro')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='etl.dashboardetl', verbose_name='Erros')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InconsistencyETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inconsistency', models.CharField(blank=True, choices=[('OS sem movimentação', 'Tasklessmovement'), ('Movimentação sem processo', 'Movementlessprocess'), ('OS em Pasta Inativa', 'Taskinativefolder'), ('O valor preenchido no campo comarca não foi encontrado como Comarca, Cidade ou Complemento de comarca', 'Invalidcourtdistrict'), ('O campo comarca não foi preenchido', 'Blankcourtdistrict'), ('O campo prazo fatal não foi preenchido', 'Blankfinaldeadlinedate'), ('O prazo fatal da OS é menor que o mínimo configurado', 'Minhouroserror')], max_length=150, null=True, verbose_name='Inconsistência')),
                ('solution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solução')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
