# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import financial.enums
import financial.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('legacy_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado')),
                ('system_prefix', models.CharField(blank=True, choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'), ('eLaw', 'Elaw')], max_length=255, null=True, verbose_name='Prefixo do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custos',
                'db_table': 'cost_center',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportServicePriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('file_xls', models.FileField(upload_to=financial.models.get_dir_name, verbose_name='Arquivo')),
                ('log', models.TextField(null=True, verbose_name='Log')),
                ('start', models.DateTimeField(verbose_name='Início processo')),
                ('end', models.DateTimeField(null=True, verbose_name='Fim processo')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Arquivos Importados de Tabela de Preços',
            },
        ),
        migrations.CreateModel(
            name='PolicyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('category', models.CharField(choices=[('DEFAULT', 'Padrão'), ('PUBLIC', 'Público'), ('NETWORK', 'Rede')], max_length=255, verbose_name='Categoria')),
                ('billing_moment', models.CharField(choices=[('PRE_PAID', 'Pré-pago'), ('POST_PAID', 'Pós-pago')], max_length=255, verbose_name='Momento do faturamento')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Tipo de Preço',
                'verbose_name_plural': 'Tipos de Preço',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('legacy_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado')),
                ('system_prefix', models.CharField(blank=True, choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'), ('eLaw', 'Elaw')], max_length=255, null=True, verbose_name='Prefixo do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Valor')),
                ('value_to_receive_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('value_to_receive', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(Decimal('0.00'), 'BRL'), max_digits=9, verbose_name='Valor a receber')),
                ('value_to_pay_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('value_to_pay', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(Decimal('0.00'), 'BRL'), max_digits=9, verbose_name='Valor a pagar')),
                ('rate_type_receive', models.CharField(choices=[('PERCENT', 'Percentual'), ('VALUE', 'Valor')], default=financial.enums.RateType['PERCENT'], max_length=10, verbose_name='Tipo de taxa a receber')),
                ('rate_type_pay', models.CharField(choices=[('PERCENT', 'Percentual'), ('VALUE', 'Valor')], default=financial.enums.RateType['PERCENT'], max_length=10, verbose_name='Tipo de taxa a pagar')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_city', to='core.city', verbose_name='Cidade')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_client', to='core.person', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tabela de preço de serviços',
                'verbose_name_plural': 'Tabelas de preço de serviços',
                'db_table': 'service_price_table',
                'ordering': ['value'],
            },
        ),
    ]
