# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('financial', '0001_initial'),
        ('lawsuit', '0001_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricetable',
            name='court_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_court_district', to='lawsuit.courtdistrict', verbose_name='Comarca'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='court_district_complement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_court_district_complement', to='lawsuit.courtdistrictcomplement', verbose_name='Complemento de comarca'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='office_correspondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_correspondent', to='core.office', verbose_name='Escritório Correspondente'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='office_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_network', to='core.officenetwork', verbose_name='Rede de escritórios'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='policy_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_prices', to='financial.policyprice', verbose_name='Tipo de preço'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_state', to='core.state', verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='servicepricetable',
            name='type_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_type_task', to='task.typetask', verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('name', 'office', 'legacy_code')},
        ),
    ]
