# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_chats', to='core.company'),
        ),
        migrations.AddField(
            model_name='chat',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='chat',
            name='offices',
            field=models.ManyToManyField(related_name='chats', to='core.office'),
        ),
        migrations.AddField(
            model_name='message',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.message'),
        ),
        migrations.AddField(
            model_name='userbychat',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='userbychat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='chat.chat', verbose_name='chat'),
        ),
        migrations.AddField(
            model_name='userbychat',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='userbychat',
            name='user_by_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='user_by_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.userbychat'),
        ),
        migrations.AddIndex(
            model_name='userbychat',
            index=models.Index(fields=['user_by_chat_id'], name='chat_userby_user_by_403017_idx'),
        ),
        migrations.AddIndex(
            model_name='unreadmessage',
            index=models.Index(fields=['user_by_message_id'], name='chat_unread_user_by_a473e6_idx'),
        ),
    ]
