# Generated by Django 5.2.17 on 2026-09-08 20:04

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Codigo')),
                ('schema', models.JSONField(blank=True, default=dashboard.models.default_bar_schema, null=True, verbose_name='Schema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Codigo')),
                ('schema', models.JSONField(blank=True, default=dashboard.models.default_card_schema, null=True, verbose_name='Schema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('refresh', models.IntegerField(blank=True, null=True, verbose_name='Refresh por millesegundo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardBarChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequencia')),
                ('bar_chart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.barchart')),
                ('dashboard', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
            options={
                'ordering': ['sequence'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='barchart',
            name='dashboards',
            field=models.ManyToManyField(blank=True, related_name='bar_charts', through='dashboard.DashboardBarChart', to='dashboard.dashboard'),
        ),
        migrations.CreateModel(
            name='DashboardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequencia')),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.card')),
                ('dashboard', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
            options={
                'ordering': ['sequence'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='dashboards',
            field=models.ManyToManyField(blank=True, related_name='cards', through='dashboard.DashboardCard', to='dashboard.dashboard'),
        ),
        migrations.CreateModel(
            name='DashboardDoughnutChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequencia')),
                ('dashboard', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
            options={
                'ordering': ['sequence'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardLineChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequencia')),
                ('dashboard', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
            options={
                'ordering': ['sequence'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoughnutChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Codigo')),
                ('schema', models.JSONField(blank=True, default=dashboard.models.default_doughnut_schema, null=True, verbose_name='Schema')),
                ('dashboards', models.ManyToManyField(blank=True, related_name='doughnut_charts', through='dashboard.DashboardDoughnutChart', to='dashboard.dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dashboarddoughnutchart',
            name='doughnut_chart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.doughnutchart'),
        ),
        migrations.CreateModel(
            name='LineChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Codigo')),
                ('schema', models.JSONField(blank=True, default=dashboard.models.default_line_schema, null=True, verbose_name='Schema')),
                ('dashboards', models.ManyToManyField(blank=True, related_name='line_charts', through='dashboard.DashboardLineChart', to='dashboard.dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dashboardlinechart',
            name='line_chart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.linechart'),
        ),
    ]
