# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
import ecm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('legacy_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado')),
                ('system_prefix', models.CharField(blank=True, choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'), ('eLaw', 'Elaw')], max_length=255, null=True, verbose_name='Prefixo do sistema')),
                ('model_name', models.CharField(max_length=120, verbose_name='Model')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='ID do Registro')),
                ('file', models.FileField(upload_to=ecm.models.get_uploda_to, verbose_name='Arquivo')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('exibition_name', models.CharField(max_length=255, verbose_name='Nome de Exibição')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DefaultAttachmentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Regra de Anexo Padrão',
                'verbose_name_plural': 'Regras de Anexo Padrão',
                'ordering': ['-id'],
            },
        ),
    ]
