# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ecm', '0001_initial'),
        ('lawsuit', '0001_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultattachmentrule',
            name='court_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lawsuit.courtdistrict', verbose_name='Comarca'),
        ),
        migrations.AddField(
            model_name='defaultattachmentrule',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='defaultattachmentrule',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='defaultattachmentrule',
            name='person_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_customer', to='core.person', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='defaultattachmentrule',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.state', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='defaultattachmentrule',
            name='type_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.typetask', verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultattachmentrule',
            unique_together={('name', 'office')},
        ),
    ]
