# Generated by Django 5.2.17 on 2026-09-08 20:04

import django.db.models.deletion
import manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('template_key', models.CharField(choices=[('DEFAULT_CUSTOMER', 'Cliente padrão'), ('DUPLICATE_PROCESS', 'Duplicar número de processo'), ('EMAIL_NOTIFICATION', 'E-mail de notificação'), ('USE_SERVICE', 'Equipe conferência dados'), ('USE_ETL', 'Importa dados de outros sistemas'), ('MIN_HOUR_OS', 'Limite para abertura de OS'), ('I_WORK_ALONE', 'Trabalho sozinho'), ('DEFAULT_USER', 'Usuário padrão')], max_length=255, unique=True, verbose_name='Chave')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('BOOLEAN', 'Boleano'), ('FOREIGN_KEY', 'Chave estrangeira'), ('DECIMAL', 'Decimal'), ('INTEGER', 'Inteiro'), ('LIST', 'Lista de opções'), ('LONG_TEXT', 'Texto Longo'), ('SIMPLE_TEXT', 'Texto Simples')], max_length=15, verbose_name='Tipo')),
                ('parameters', models.JSONField(verbose_name='Características disponíveis')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de configuração',
                'verbose_name_plural': 'Templates de configuração',
                'ordering': ('name', 'type'),
            },
        ),
        migrations.CreateModel(
            name='TemplateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('value', models.JSONField(blank=True, default=manager.models.default_template_value, null=True, verbose_name='Valor')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_office', to='core.office', verbose_name='Escritório')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.template', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Configuração por escritório',
                'verbose_name_plural': 'Configurações por escritório',
                'ordering': ('office', 'template'),
            },
        ),
    ]
